In [5]:
import torch
import math
torch.set_grad_enabled(False)

In [ ]:
#build networks combining fully connected layers, Tanh, and ReLU,
#run the forward and backward passes,
#optimize parameters with SGD for MSE.

In [ ]:
class Module(object):
    def forward(self , *input):
        raise NotImplementedError
    def backward(self , *gradwrtoutput):
        raise NotImplementedError
    def param(self): 
        return []

# LINEAR

In [ ]:
#LINEAR MODULE (FULLY CONNECTED LAYER)
class Linear(object):
    def __init__(self):
        k_root = math.sqrt(1/in_feature)
        self.weight = torch.empty(in_feature,out_feature).uniform_(-k_p,k_p)
        self.bias = torch.empty(out_feature).uniform_(-k_p,k_p)
    
    def forward(self , *input, in_feature, out_feature):
        if(isinstance(input, tuple)):
            liste = []
            t = input[0]
            for x in t:
                liste.append(x.matmul(weight)+bias) 
            output = tuple(liste)
        else:
            output = input.matmul(weight)+bias  
        
    def backward(self , *gradwrtoutput):
        raise NotImplementedError
        
    def param(self):
        output = [self.weight, self.grad_weight, self.bias, self.grad_bias]
        [bias, grad_bias]
        return []
    
    #https://pytorch.org/docs/stable/nn.html#linear-layers
    
#forward should get for input, and returns, a tensor or a tuple of tensors.

#backward should get as input a tensor or a tuple of tensors containing the gradient of the 
#loss with respect to the module’s output, accumulate the gradient wrt the parameters, 
#and return a tensor or a tuple of tensors containing the gradient of the loss wrt the module’s input.

#param should return a list of pairs, each composed of a parameter tensor, and a gradient tensor of same size. 
#This list should be empty for parameterless modules (e.g. ReLU).
#Some modules may requires additional methods, and some modules may keep track of information from the forward 
#pass to be used in the backward.

In [39]:
x1 = torch.empty(3,4,7,10).normal_()
print(x1)
in_feature = 10
out_feature = 2
k = 1/in_feature
k_p = math.sqrt(k)
y = torch.empty(in_feature,out_feature).uniform_(-k_p,k_p)
print(y)
bias = torch.empty(out_feature).uniform_(-k_p,k_p)
print(bias)
print(bias.size())
z1 = x1.matmul(y) + bias
print(z1.size())

tensor([[-0.0678, -0.0091],
        [ 0.3138,  0.0206],
        [ 0.0406,  0.1020],
        [-0.0521, -0.2344],
        [ 0.0756, -0.2297],
        [ 0.3056,  0.0490],
        [-0.0034,  0.0890],
        [ 0.0847,  0.1470],
        [ 0.2353, -0.0367],
        [ 0.3008, -0.2754]])
tensor([ 0.2924, -0.2238])
torch.Size([2])
torch.Size([3, 4, 7, 2])


# RELU

In [146]:
#RELU MODULE
class ReLU():
    def __init__(self):
        self.input = None
        self.grad = None
    
    def forward(self, *input): 
        liste = []
        self.input = input
        for x in input:
            liste.append(torch.max(x,torch.empty(x.size(0), x.size(1)).fill_(0))) 
        output = tuple(liste)
        return output
        
    def backward(self, *gradwrtoutput):
        liste = []
        self.grad = gradwrtoutput
        for x in self.input:
            liste.append((x.sign()+1)/2) 
            #Si >0, sign donne 1, +1 /2 donc 1 (d(x)/dx = 1)
            #Si =0, sign donne 0, +1 /2 donc 0.5 => Normalement on a pas de cas qui vaut 0, mais à voir
            #Si <0, sign donne -1, +1 /2 donc 0 (d(0)/dx = 0) 
        print('liste')
        print(tuple(liste))
        for (x,y) in (liste, self.grad)
            new.append(x+y)
        print('liste+grad')
        print(tuple(new))
        #output = tuple(liste)
        return new   

    def param(self): 
        return []
    
#backward should get as input a tensor or a tuple of tensors containing the gradient of the 
#loss with respect to the module’s output, accumulate the gradient wrt the parameters, 
#and return a tensor or a tuple of tensors containing the gradient of the loss wrt the module’s input.

#param should return a list of pairs, each composed of a parameter tensor, and a gradient tensor of same size. 
#This list should be empty for parameterless modules (e.g. ReLU).
#Some modules may requires additional methods, and some modules may keep track of information from the forward 
#pass to be used in the backward.

SyntaxError: invalid syntax (<ipython-input-146-5aa742f72be8>, line 25)

In [142]:
T = ReLU()
x = torch.empty(1,2).fill_(1)
y = torch.empty(1,2).fill_(-2)
grad1 = torch.empty(1,2).fill_(0)
grad2 = torch.empty(1,2).fill_(0)
print(x)
print(y)
t = T.forward(x, y)
print('ReLU of x, y')
print(t)
grad = T.backward(grad1,grad2)
print('grad')
print(grad)
p = T.param()
print(p)

tensor([[1., 1.]])
tensor([[-2., -2.]])
ReLU of x, y
(tensor([[1., 1.]]), tensor([[0., 0.]]))
liste
(tensor([[1., 1.]]), tensor([[0., 0.]]))
liste+grad
[tensor([[1., 1.]]), tensor([[0., 0.]]), tensor([[0., 0.]]), tensor([[0., 0.]])]
grad
(tensor([[1., 1.]]), tensor([[0., 0.]]), tensor([[0., 0.]]), tensor([[0., 0.]]))
[]


In [154]:
x = torch.empty(1,2).fill_(1)
y = torch.empty(1,2).fill_(-3)
z = torch.empty(1,2).fill_(0)
t = (x > torch.empty(x.size()).fill_(0))
t2 = (y.sign()+1)/2
t3 = (z.sign()+1)/2
print(x, t)
print(y, t2)
print(z, t3)

tensor([[1., 1.]]) tensor([[True, True]])
tensor([[-3., -3.]]) tensor([[0., 0.]])
tensor([[0., 0.]]) tensor([[0.5000, 0.5000]])


# TANH

In [178]:
#TANH MODULE
class Tanh():
    def __init__(self):
        self.input = None
        
    def forward(self, *input): 
        liste = []
        self.input = input
        for x in input:
            liste.append(torch.tanh(x)) 
        output = tuple(liste)
        return output
    
    def backward(self, *gradwrtoutput):
        liste = []
        for x in self.input:
            liste.append(1 - torch.tanh(x).pow(2))
        output = gradwrtoutput*tuple(liste)
        return output

    def param(self):
        return [] #Pas de param


#forward should get for input, and returns, a tensor or a tuple of tensors.

#backward should get as input a tensor or a tuple of tensors containing the gradient of the 
#loss with respect to the module’s output, accumulate the gradient wrt the parameters, 
#and return a tensor or a tuple of tensors containing the gradient of the loss wrt the module’s input.

#param should return a list of pairs, each composed of a parameter tensor, and a gradient tensor of same size. 
#This list should be empty for parameterless modules (e.g. ReLU).
#Some modules may requires additional methods, and some modules may keep track of information from the forward 
#pass to be used in the backward.

In [179]:
T = Tanh()
x = torch.empty(1,2).fill_(1)
y = torch.empty(1,2).fill_(2)
print(x)
print(y)
t = T.forward(x, y)
print('tanh of x, y')
print(t)
grad = T.backward()
print('grad')
print(grad)
p = T.param()
print(p)

tensor([[1., 1.]])
tensor([[2., 2.]])
tanh of x, y
(tensor([[0.7616, 0.7616]]), tensor([[0.9640, 0.9640]]))


TypeError: can't multiply sequence by non-int of type 'tuple'

# LOSSMSE (normalement juste, toujours à la fin)

In [174]:
#LOSSMSE MODULE
#Maybe: convert to list/tensor the tuple
    
class LossMSE():
    def __init__(self):
        self.loss = None
        self.gradloss = None
    
    def forward(self, *input, target): #Si plusieurs input et target comment on fait?
        liste = []
        for x in input:
            liste.append((x-target).pow(2)) 
        output = tuple(liste)
        self.loss = output
        return output
        
    def backward(self):
        liste = []
        for x in self.loss:
            liste.append(2*((x).pow(1/2))) #on obtient 2*(sqrt((x-target).pow(2))) du coup 2*(x-target)
        output = tuple(liste)      
        self.gradloss = output
        return output

    def param(self):
        return [] #No param
#forward should get for input, and returns, a tensor or a tuple of tensors.

#backward should get as input a tensor or a tuple of tensors containing the gradient of the 
#loss with respect to the module’s output, accumulate the gradient wrt the parameters, 
#and return a tensor or a tuple of tensors containing the gradient of the loss wrt the module’s input.

#param should return a list of pairs, each composed of a parameter tensor, and a gradient tensor of same size. 
#This list should be empty for parameterless modules (e.g. ReLU).
#Some modules may requires additional methods, and some modules may keep track of information from the forward 
#pass to be used in the backward.

In [180]:
N = LossMSE()
x = torch.empty(1,2).fill_(1)
y = torch.empty(1,2).fill_(2)
print(x)
print(y)
t = torch.empty(1,2).fill_(-1)
t2 = torch.empty(1,2).fill_(-1)
print(t)
l = N.forward(x, y ,t,t2)
print('loss')
print(l)
dl = N.backward()
print('dloss')
print(dl)
p = N.param()
print(p)

tensor([[1., 1.]])
tensor([[2., 2.]])
tensor([[-1., -1.]])


TypeError: forward() missing 1 required keyword-only argument: 'target'

# SEQUENTIAL

In [ ]:
#SEQUENTIAL MODULE (to combine several modules in basic sequential structure)
class Sequential(object):
    def forward(self , *input):
        raise NotImplementedError
    def backward(self , *gradwrtoutput):
        raise NotImplementedError
    def param(self): 
        return []
    
#forward should get for input, and returns, a tensor or a tuple of tensors.

#backward should get as input a tensor or a tuple of tensors containing the gradient of the 
#loss with respect to the module’s output, accumulate the gradient wrt the parameters, 
#and return a tensor or a tuple of tensors containing the gradient of the loss wrt the module’s input.

#param should return a list of pairs, each composed of a parameter tensor, and a gradient tensor of same size. 
#This list should be empty for parameterless modules (e.g. ReLU).
#Some modules may requires additional methods, and some modules may keep track of information from the forward 
#pass to be used in the backward.

# Test.py

In [34]:
training_set = torch.empty(1000,2).uniform_(0,1)  #x et y
training_classes = torch.empty(1000,1)
testing_set = torch.empty(1000,2).uniform_(0,1)  #x et y
testing_classes = torch.empty(1000,1)

r = torch.empty(1,1).fill_(1/(2*math.pi)).pow(1/2)

for i in range (1000):
    if (training_set[i].pow(2).sum()).pow(1/2).item() < r.item():
        training_classes[i] = 1
    else:
        training_classes[i] = 0
    
    if (testing_set[i].pow(2).sum()).pow(1/2).item() < r.item():
        testing_classes[i] = 1
    else:
        testing_classes[i] = 0

#builds a network with two input units, two output units, three hidden layers of 25 units,
#trains it with MSE, logging the loss,
#computes and prints the final train and the test errors.